### ISSUE TITLE
Persistent directory concers discussion

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf#1]
Hello

I liked the courage to package this program, I read your submission and why you chose the gnome platform, the system does use an old jdk, it also uses outdated ciphers for receitanet (the distribuitons is considering such cipher as legacy).

I have a discussion last year about some permission of IRPF, a concern what have another persistent files and directory.

https://github.com/farribeiro/irpf-flatpak/pull/5

I hope you appreciate the issue and I just didn't publish my solution for fears with the government (Note it's functional without browser workaround and patches).

if you liked any yaml entry of my solution and want improve your solution, feel free to copy it[1] , especially the proprietary tag or even the README snippets

[1] no attribution of authorship required

CC @realgrm

**Comment by guihkx** [comment]
Hey, thanks for reaching out. 

>I liked the courage to package this program

Hahah I get where you're coming from, but I really doubt the government will bark at us for redistributing this, but if they do, I'll gladly remove the app from Flathub.

>it also uses outdated ciphers for receitanet (the distribuitons is considering such cipher as legacy).

Sorry, I don't quite understand what you mean by this. Can you elaborate, please?

>concern what have another persistent files and directory.

I've read the comments on that issue, but I'm honestly not a big fan of giving read/write access to the entire home folder. However, I'm happy to re-evaluate this, in case we're breaking some core functionality of the program.

>(Note it's functional without browser workaround and patches).

I think so, but having clickable links not doing anything, is a *really* bad user experience. Additionally, I'm sure you're aware that this year they added a button to login using your gov.br account, which is a really useful feature that won't work with unless we're using the GNOME runtime with the additional dbus permissions:

![image](https://user-images.githubusercontent.com/626206/159543173-6b02cee6-5a79-42cb-a8e1-ccdde135558d.png)

That being said, I'll take a closer look at the manifest and README, there's definitely useful information that can also be added here.

(But feel free to contribute with a PR as well)

Thank you!

**Comment by farribeiro** [comment]
>Sorry, I don't quite understand what you mean by this. Can you elaborate, please?

a commentary that I saw that the ciphers what especially receitanet in jdk17 (and why it asks for version 11) considered legacy... and thus it needs modifications in jdk accepts olds cipher. Those who have installed it on their systems (without sandbox) have resorted to this article. A link to manage cipher on jdk:

https://java.com/en/configure_crypto.html

**PS**: was what they reported about three years ago

> I've read the comments on that issue, but I'm honestly not a big fan of giving read/write access to the entire home folder. However, I'm happy to re-evaluate this, in case we're breaking some core functionality of the program.

Me too. Unfortunately don't know what else it creates, the best option I've seen is to give access to HOME

> I think so, but having clickable links not doing anything, is a really bad user experience. Additionally, I'm sure you're aware that this year they added a button to login using your gov.br account, which is a really useful feature that won't work with unless we're using the GNOME runtime with the additional dbus permissions:

I noticed what the links failed (btw... i cloud not reproduce again), the app not release the link, in the main page... no menu or close button actions 

>  they added a button to login using your gov.br account

Do redirects work to sandbox? oh IPC !

Your work is to be congratulated

**Comment by farribeiro** [comment]
I think the shared module has dbus... Let's take a look

Have this... https://github.com/flathub/shared-modules/tree/master/dbus-glib

Just put as submodule in your project

**Comment by guihkx** [comment]
Have you tried that module alone to see if it works? I haven't, but I don't think it will work, to be honest. Java internally calls either `gtk_show_uri()`/ `gnome_url_show()` from GTK3/GNOME libraries (respectively). So I think unless these libraries are present, it won't work...

There's a [proposed patch](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/16) that would make opening links work seamlessly without having to use the GNOME runtime, but judging by the maintainer's response, I don't think it will be accepted as-is.

**Comment by guihkx** [comment]
I'm still a bit confused about that whole crypto thing, though. Are you just informing me the reason why they recommend using OpenJDK 11 instead of 17, i.e. because of change in cryptography? Or something breaks in OpenJDK 11?

>Me too. Unfortunately don't know what else it creates, the best option I've seen is to give access to HOME

Having been using the Flatpak version for about a year now, I still haven't found any problems (*yet*). But let's see, maybe with more people using it via Flatpak, some new issues might arise. (hopefully not, though 😄 )

>Do redirects work to sandbox? oh IPC !

From what I could tell, the way it works is pretty simple actually: After you click the "gov.br login" button, IRPF temporarily opens a local web server and awaits until you authenticate yourself on your browser. After the successful authentication on gov.br, you are redirected to the local web server IRPF is listening on, so they can get the authentication token.

**Comment by farribeiro** [comment]
> Have you tried that module alone to see if it works? I haven't, but I don't think it will work, to be honest. Java internally calls either `gtk_show_uri()`/ `gnome_url_show()` from GTK3/GNOME libraries (respectively). So I think unless these libraries are present, it won't work...
> 
> There's a [proposed patch](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/16) that would make opening links work seamlessly without having to use the GNOME runtime, but judging by the maintainer's response, I don't think it will be accepted as-is.

Indeed.

**Comment by farribeiro** [comment]
> Or something breaks in OpenJDK 11?

yes. i think the opendk11 crypto in v17 is deprecated (legacy)

> Having been using the Flatpak version for about a year now, I still haven't found any problems (yet). But let's see, maybe with more people using it via Flatpak, some new issues might arise. (hopefully not, though smile )

I asked in the flatpak room in the matrix about the `lib/resources` directory to be persisted or a symlink to not build a new package with every dataset/database update, I get that it is immutable (I expected there to be a workaround) where the app is

**Comment by guihkx** [comment]
Ah, yes, there was a brief discussion about this issue on the PR I sent:

https://github.com/flathub/flathub/pull/2935#pullrequestreview-914122369

It seems that the only solution right now is to create a wrapper script that installs everything to `~/.var/app/br.gov.fazenda.receita.irpf`.

Personally, I'm not a big fan of the approach above, and I think what we have now is just fine. However, I'd be happy to evaluate a new approach, in case someone has the interest of implementing it, of course.

**Comment by guihkx** [comment]
I think the main points were already addressed, so I'll close this.

Nevertheless, feel free to re-open if you think I left out something.

Thanks.
