### ISSUE TITLE
Metadatas not showing on GNOME Software

### ISSUE THREAD

**Issue by ghost** [flathub/br.gov.fazenda.receita.irpf#20]
As mentioned, the metadata aren't showing on GNOME Software, even though they appear on Flathub. Neither the description nor app image.

**Comment by guihkx** [comment]
Maybe it's a temporary issue? Everything is showing up here:

![image](https://user-images.githubusercontent.com/626206/169401798-3b2bd930-0cee-4670-8c88-d6da2f6a1382.png)

![image](https://user-images.githubusercontent.com/626206/169401899-a230129b-1df7-4e82-a9ec-d9e694c0abff.png)

Can you check again, please?

**Comment by guihkx** [comment]
Well, this is not really under our control; Plus, our metadata is okay and always validated by appstream.

Closing.
