### ISSUE TITLE
Gnome new Platform

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf#31]
Gnome project released the v43 platform and SDK

I recommend evaluating the change, and Or don't heed this issue

Why not a PR ? I want notice and the owner make tests

**Comment by guihkx** [comment]
Oh, right. Thanks for the reminder, I think it's always preferable to run on the latest runtime available, as long as everything still works as before, of course. 😀

Could you open a pull request? That way we could easily test the build generated by the Flathub bot.

But don't feel obligated right now, as I think I'll only be able to test it by the weekend.
Thanks!
------- Original Message -------

**Comment by farribeiro** [comment]
The freedesktop and gnome Platform is released, just the kde not released yet

I see the app will broke because the openjdk (11 either 17) not updated to new plataform

**Comment by guihkx** [comment]
Right, it depends on https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/28 being merged
------- Original Message -------
