### ISSUE TITLE
Crie um flatpak do DITR 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/br.gov.fazenda.receita.irpf#40]
https://www.gov.br/receitafederal/pt-br/centrais-de-conteudo/download/pgd/ditr

Desculpa por entrar em contato desse jeito!

https://community.endlessos.com/t/como-instalar-ditr-2022-no-endless/19906?u=leandrostanger

**Comment by guihkx** [comment]
>Desculpa por entrar em contato desse jeito!

Imagina, sem problemas.

Mas desculpa, como eu não uso (e nunca usei) o DITR, no momento não tenho interesse nem recursos para criar e manter um Flatpak dele... :/

Espero que entenda. ^^

Abraço.
