### ISSUE TITLE
Single sign-on (SSO) não funciona com Firefox flatpak

### ISSUE THREAD

**Issue by herzenschein** [flathub/br.gov.fazenda.receita.irpf#53]
Acho uma boa ideia deixar isso escrito e encontrável em algum lugar, achei melhor aqui:

O aplicativo do IRPF parece ter uma hard dependency com o GVFS, que não vem instalado em sistemas tradicionais com Plasma. Por alguma razão isso faz com que o SSO não funcione se o navegador estiver como flatpak (uso Firefox assim).

Isso é mais problemático em distros imutáveis como Fedora Kinoite ou openSUSE MicroOS Desktop, mas não faz mal, só instalar no sistema. Instalar o GVFS no sistema após instalar o aplicativo do IRPF do site faz o single sign-on funcionar.

Mas o workaround não funciona com o flatpak do IRPF por alguma razão. Eu suspeito que o problema é https://github.com/flatpak/xdg-desktop-portal/issues/519 e https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/15.

---

I thought it would be a good idea to leave this here and make it findable for whoever faces the same problem:

The app seems to have a hard dependency on GVFS, which doesn't come installed in usual Plasma systems. For some reason this breaks SSO if the browser being used is a flatpak (in my case, Firefox).

This is a bit of a problem in immutable distros like Fedora Kinoite or openSUSE MicroOS Desktop, but that's not such a big deal, I just have to install GVFS. Installing it and the app from the website works fine.

But this workaround doesn't work with the IRPF flatpak for some reason. I suspect the problem is (mentioned in the two links above).

**Comment by guihkx** [comment]
Podia jurar que da última vez que testei o app numa máquina virtual com KDE Plasma, o SSO funcionava, e não precisei instalar nenhuma dependência. :/

Vou investigar.

**Comment by guihkx** [comment]
Confirmo que SSO e abrir links no geral não funciona no Fedora Kinoite.

Mas preparei uma build com um patch experimental que, nos meus testes, fez tudo funcionar independente de distro ou de pacotes instalados no sistema. Se quiser testar, tem uma build recente dela aqui:

https://github.com/flathub/flathub/pull/4095#issuecomment-1520538709

Este patch não foi incluso aqui porque é uma modificação (embora pequena) a um programa proprietário. Então achei melhor saber da opinião dos admins do Flathub primeiro.

**Comment by guihkx** [comment]
Bug corrigido durante a migração para outro app id (br.gov.fazenda.receita.irpf2023):

https://github.com/flathub/br.gov.fazenda.receita.irpf2023/commit/ba29ce2541e94129015794670bb412dcd7f80cc2
