### ISSUE TITLE
Versionamento

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf#54]
Olá,

Recebi uma DM no telegram com o seguinte conteúdo:

> Miguilim escreveu 
> Então, eu vi que agora o que está disponível é o IRPF 2023, como se o de 2022 tivesse sido atualizado
>
> Mas acredito que o conceito de "atualizar" de 2022 pra 2023 esteja errado. O ideal seria que os dois (e de anos anteriores) estivessem disponível, como aplicativos distintos
>
> Pois cada IRPF 20XX é referente a um Ano-calendário específico, o de 2023 é refente ao ano de 2022, e o de 2022 é referente ao ano de 2021
>
> Um exemplo disso na pratica seria que, a receita federal ela pode negar o meu imposto de renda de 2021 (pois só foi processado, mas não aceito ainda), e pra eu alterar, eu teria que ter o programa de 2022, pois o de 2023 não serve pra isso

PS: Ao que entendo o conceito que usamos é o declaração do ano corrente. Mas tbm entendo que a modelo não está errada.

PS: Eu tbm vou precisar retificar minha declaração. Mas neste caso usaria numa VM ou containers 

PS: Sempre reparei que a Receita Federal cada ano lança um programa distinto e não é continuação do ano anteriores, sempre numerado o primeiro release como v1. Podíamos dizer IRPF2023 v1

**Comment by miguilimzero** [comment]
Exatamente. O IRPF 2023 não deveria ser considerado uma atualização do 2022. A Receita Federal desenvolve e distribui o IRPF, considerando cada ano um programa diferente.

Você não consegue usar o IRPF 2023 para fazer a declaração de um Ano-calendário diferente/anterior de 2022.

**Comment by guihkx** [comment]
A única saída que eu vejo para esse "problema", seria o usuário efetuar manualmente o [*downgrade*](https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading) da versão atual (seja qual for ela), para a última versão 2022 que foi empacotada, ou seja:

```
$ sudo flatpak update --commit=f0b1803127e4421450ecda0d8e08dfab7296127e1ecb337aa8854975eef25ba1 br.gov.fazenda.receita.irpf
```

Até hoje nunca precisei retificar minhas declarações, então não sei fazer o downgrade desse jeito funcionaria.

Se alguém puder testar e me confirmar que funciona, posso documentar isso no README.

**Comment by farribeiro** [comment]
@guihkx a sugestão dele é... Fazer um flatpak por ano. Submetendo um novo app a cada ano

PS: O IRPF2022 muito provavelmente  continua recebendo atualizações

**Comment by guihkx** [comment]
> Fazer um flatpak por ano.

Pode ser, mas não tenho certeza se essa é a melhor opção (ou se os mantenedores do Flathub aceitariam isso).

Eu sei que tem como a gente criar branches extras aqui nesse repositório, mas não sei se funcionaria no nosso caso. Se funcionar, eu poderia criar branches diferentes para cada versão anual do programa, ou algo do tipo...

Mas, em último caso, pra mim está claro que este é um problema estrutural com o aplicativo em si, que requer que o usuário utilize uma versão antiga do programa para fazer a retificação.

>O IRPF2022 muito provavelmente continua recebendo atualizações

Aparentemente esse parece ser realmente o caso, o que é triste.

**Comment by miguilimzero** [comment]
> Pode ser, mas não tenho certeza se essa é a melhor opção (ou se os mantenedores do Flathub aceitariam isso).

Bom, teria que tentar explicar que são programas diferentes. Porque infelizmente é feito dessa forma.

> Mas, em último caso, pra mim está claro que este é um problema estrutural com o aplicativo em si, que requer que o usuário utilize uma versão antiga do programa para fazer a retificação.

Então, isso é uma visão incorreta de como o IRPF é feito, não é um problema estrutural e nem uma versão antiga. São programas diferentes. Da mesma forma que tem o FIFA 20, 21, 22, 23, tem o IRPF 2020, IRPF 2021, IRPF 2022, IRPF2023.

**Comment by guihkx** [comment]
>Bom, teria que tentar explicar que são programas diferentes. Porque infelizmente é feito dessa forma.

Eu perguntei no canal do Flathub no Matrix, quando eles responderem eu atualizo aqui.

>Então, isso é uma visão incorreta de como o IRPF é feito, não é um problema estrutural e nem uma versão antiga. São programas diferentes. Da mesma forma que tem o FIFA 20, 21, 22, 23, tem o IRPF 2020, IRPF 2021, IRPF 2022, IRPF2023.

Não concordo com a analogia. Um é um jogo pago, feito com uma finalidade totalmente diferente do IRPF.

Ninguém vai conseguir me convencer de que existe uma limitação técnica *real* que impeça os desenvolvedores de adicionarem a funcionalidade de retificação de declarações anteriores em versões recentes do IRPF. LOL

**Comment by farribeiro** [comment]
Quero reforçar que branches pode ser confuso para leigos que desconhecem esse funcionamento do Flathub

Só não tem GUI pra trocar entre eles

**Comment by farribeiro** [comment]
Debatemos no grupo de telegram sobre flatpak brasileiro e alguém solta este comentário:

> A questão do Irpf é real, se não fizer totalmente separado por ano é possivel de terem um problema sério em algum momento.
O app é incremental, mas travado a ano calendário de ref. Por causa das resoluções normativas do País, ano contábil, fiscal, etc.
Tem coisas que se vc declarar em 2020 é completamente dif. de 2022...
>
> ...

**Comment by guihkx** [comment]
Eu entendo que está estabelecido que atualmente é, no mínimo, incoveniente retificar declarações de anos passados.

>é possivel de terem um problema sério em algum momento.

No entanto, não entendo o que o comentário acima esteja insinuando. Para usos "normais", ou seja, quando não há necessidade de retificação, o app funciona como deve... Ou não?

**Comment by farribeiro** [comment]
> Só não tem GUI pra trocar entre eles

O @cleomenezesjr comentou o seguinte a respeito da usabilidade do app:

> Criar um instalador ✅

PS: Extra-data com persistência -- eis minha aposta -- Pq o app não dá pra ser imutável

PS: Sabe o que você fez me lembrar? Do heroic, um launcher

PS: tb lembrei que o Bottles está trabalhando em garrafas Linux

**Comment by guihkx** [comment]
Criar uma espécie de instalador ou interface dedicada para trocar de versão desse jeito me parece over-engineered.

>PS: Extra-data com persistência

Eu já expus minha opinião sobre usar `extra-data` no passado, mas só reiterando: Sou fortemente contra.

No entanto, se alguém se comprometer em criar *e* manter uma espécie de wrapper para gerenciar a instalação do IRPF, sinta-se livre para enviar um pull request para análise. 

Mas particularmente, não tenho nenhum interesse em substituir o status quo por `extra-data`, pois:

- A utilização de um wrapper não-oficial torna o app mais complicado de se manter
- Tornaria a deduplicação de arquivos do repositório OStree global menos efetiva (porque os arquivos seriam instalados fora dele)
- Tornaria incrivelmente complicada a [verificação de integridade e de reparo automático](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-repair) dos arquivos do app em caso de corrompimento de dados

Na minha opinião, no geral as perdas seriam maiores que os ganhos.

>Pq o app não dá pra ser imutável

Só não daria para ser imutável em um cenário onde uma espécie de instalador existisse (como foi proposto).

Na minha opinião, o status quo absolutamente permite que o app seja imutável.

Mas claro, se alguém estiver enfrentando algum problema causado especificamente pela imutabilidade, por favor abra uma nova issue para discutirmos uma solução.

**Comment by guihkx** [comment]
Recebi a resposta (e opinião) de um dos admins do Flathub sobre o assunto:

![image](https://user-images.githubusercontent.com/626206/232330305-0b989fa9-aba3-462c-be1c-df035499085b.png)

Então, no momento, me parece que alternativa "menos pior" é realmente criar um repositório para cada versão anual do IRPF... :(

Vou adaptar e preparar os manifests para as versões 2022 e 2023, e quando (e se) essas versões forem aceitas, irei marcar esta aqui como obsoleta.

Caso alguém precise de versões ainda mais antigas, fiquem a vontade para ser o mantenedor delas.

Caso tudo ocorra como o planejado nos próximos dias, atualizo vocês por aqui também.

Obrigado!

**Comment by farribeiro** [comment]
vc pode deixar esse projeto como a versão corrente, assim que troca de ano vc cria o repositório do ano anterior

**Comment by guihkx** [comment]
Concordo, sua ideia é melhor.

**Comment by miguilimzero** [comment]
Bom, a analogia era pra mostrar a visão de quem criar e distribui o programa, e não em refletir se isso é a melhor forma ou não, se há limitação técnica ou não...  Dado que não temos controle sobre isso. Infelizmente (porque também não acho correto) a Receita Federal cria e distribui dessa forma (um programa independente pra cada ano-calendário). 

Então a forma correta de empacotar, levando em conta a forma como a Receita Federal distribui o própio software, seria criar um repositório no Flathub para cada IRPF.

> vc pode deixar esse projeto como a versão corrente, assim que troca de ano vc cria o repositório do ano anterior

Fazer isso tambem não seria a forma correta. O IRPF salva as suas declarações "Em Preenchimento" e "Transmitidas" localmente no seu computador. Caso você tenha uma declaração do IRPF 2022, e o aplicativo for "atualizado" para o IRPF 2023, essa declaração não aparecerá mais no programa.

Claro que da para recuperar entrando na pasta do aplicativo Flatpak, mas para um usuário leigo isso pode ser bastante confuso (e até para usuários já mais experimentes, já que eles precisam ter ciência desse detalhe, pra assim começar a procurar nos diretórios do programa).

**Comment by farribeiro** [comment]
@srdante Os arquivos de declaração (do usuário) e bk são guardados/salvos fora da sandbox

**Comment by guihkx** [comment]
>Caso você tenha uma declaração do IRPF 2022, e o aplicativo for "atualizado" para o IRPF 2023, essa declaração não aparecerá mais no programa.

Não entendi. A pessoa que quiser continuar utilizando versões anteriores do IRPF, terá que baixá-las separadamente.

Eu vejo uma lógica em manter o namespace `br.gov.fazenda.receita.irpf` como a versão mais recente, e então criar pacotes para versões anteriores.

Então assim que a pessoa instalar a versão 2022 (e.g. `br.gov.fazenda.receita.irpf2022`), ela poderá acessar as declarações anteriores normalmente, pois estas são salvas por padrão em `~/ProgramasRFB/IRPF<ano>`.

**Comment by miguilimzero** [comment]
Entendo. Dessa forma realmente não teria problemas aparentes. Mas ainda acredito que a forma ideal seria um repositório para cada ano do IRPF, sem a versão "ano corrente". Não acho coerente meu IRPF 2022 "atualizar" para o de 2023, dado que são programas diferentes.  

Mas é apenas minha opinião. De qualquer forma, sou muito agradecido por ter alguém cuidando de distribuir o IRPF via Flathub, foi uma grande mão na roda pra mim no ano passado :)

**Comment by guihkx** [comment]
>Não acho coerente meu IRPF 2022 "atualizar" para o de 2023, dado que são programas diferentes.

Embora discordemos nesse ponto em específico, essa discussão me fez pensar num ponto importante (pra mim) e me fez mudar de lado novamente. :P

Não faz muito sentido eu ser o "mantenedor eterno" do namespace `br.gov.fazenda.receita.irpf`, porque caso algum imprevisto aconteça e eu não consiga mais manter o IRPF atualizado, esse namespace vai ficar inutilizado à toa, até alguém tomar controle dele, ou então ele será arquivado pelos administradores do Flathub.

Eu acho que a gente criando namespaces dedicados para versões novas e antigas do IRPF, irá permitir uma maior flexibilidade, permitindo que qualquer pessoa seja mantenedora de qualquer versão, independente de mim. 🤔 

Caso a maioria concorde com isso, nos próximos dias envio as versões 2022 (`br.gov.fazenda.receita.irpf2022`) e 2023 (`br.gov.fazenda.receita.irpf2023`) para análise e, caso sejam aceitas, arquivo esse repositório.

Mas posso estar enganado, então por favor expressem suas opiniões (contrárias ou a favor).

Grato!

**Comment by miguilimzero** [comment]
> Eu acho que a gente criando namespaces dedicados para versões novas e antigas do IRPF, irá permitir uma maior flexibilidade, permitindo que qualquer pessoa seja mantenedora de qualquer versão, independente de mim. 

Eu ainda vou começar a me aventurar com flatpaks, então acho que mais pra frente não vejo problema em ser um mantenedor. (E tambem planejo publicar o GCAP no futuro).

> Caso a maioria concorde com isso, nos próximos dias envio as versões 2022 (br.gov.fazenda.receita.irpf2022) e 2023 (br.gov.fazenda.receita.irpf2023) para análise e, caso sejam aceitas, arquivo esse repositório.

Como é a solução que eu dei força, não tem como eu dizer outra coisa. Eu concordo com essa forma :)

**Comment by farribeiro** [comment]
Estou neutro a respeito de como vai ser/nomear, desde que fique fácil para o usuário e para os mantedores tb, sem infringir copyright e licenças (que seja da maneira correta de empacotar)

**Comment by farribeiro** [comment]
@guihkx Por que vc patcheou o IRPF2023?

PS: Ninguém confia quando se fala em um app fiscal ou bancário alterações de seu funcionamento. Eu coloquei um disclaimer no meu projeto devido essas preocupações:

> For transparency, privacy and security NEVER USE ANY PRE-BUILT IMAGE FROM THIS. Obtain a copy of the source code of this repository, check the content and build your own image.

**Comment by guihkx** [comment]
Primeiramente, o patch não foi incluso neste pacote. Ele apenas foi enviado para análise dos admins do Flathub.

Mas caso ele seja aceito, na minha visão, os benefícios em utilizá-lo são maiores que os malefícios:

- A solução atual de apenas utilizar o runtime do GNOME não funciona em todos os cenários:
  - #53 (o patch corrige isto)
- A classe modificada é pequena e simples o suficiente a ponto de não ser complicada de manter, ou até mesmo introduzir bugs desnecessários
- O patch nos permite migrar para um runtime mais leve:
  - `org.gnome.Platform/x86_64/43` (atual): 863,7 MB
  - `org.freedesktop.Platform/x86_64/22.08` (novo): 575,0 MB

>PS: Ninguém confia quando se fala em um app fiscal ou bancário alterações de seu funcionamento.

Considerando que o patch é público e apenas altera uma pequena classe para fazer URLs abrirem corretamente, ou seja, corrige um problema de funcionamento *real* do aplicativo, não vejo problemas.

No mais, já temos um aviso claro na descrição do aplicativo informando aos usuários que o app não é oficial, então cabe a cada um tomar a decisão que achar melhor para si.

**Comment by farribeiro** [comment]
Sobre o tamanho do runtime platform nós já discutimos e você optou manter o gnome para... Evitar de fazer o patch, não é? Agora está mudando de posicionamento, ok!  Ainda assim considero o ponto de há quem diverge de alteração no app. 

Sobre ser público ou não no meu caso houve desconfiança mesmo publicando os yaml e demais arquivos utilizados

**Comment by guihkx** [comment]
>Sobre o tamanho do runtime platform nós já discutimos e você optou manter o gnome para... Evitar de fazer o patch, não é?

Não. Eu nunca havia cogitado patchear o app, porque até então eu acreditava que utilizar o runtime do GNOME era o suficiente para fazer tudo funcionar como devia, mas a issue #53 me provou o contrário.

>Ainda assim considero o ponto de há quem diverge de alteração no app.

Não gosto também, mas infelizmente, no momento é um "mal necessário". Porém permaneço aberto a outras ideias, então se você souber de alguma que corrija o bug linkado, por favor compartilhe.

>Sobre ser público ou não no meu caso houve desconfiança mesmo publicando os yaml e demais arquivos utilizados

Ué... Hahah

Mas é como eu disse, caso o patch seja aprovado pelos admins e alguém se sinta desconfortável com as alterações no programa, ainda terá algumas opções:

- Manter uma build pessoal do IRPF, com o patch removido (obrigado Flatpak por permitir isso!)
- Utilizar a versão oficial do governo não-modificada, que roda fora da sandbox do Flatpak e que tem acesso irrestrito a todos os arquivos do sistema, por exemplo 😬 

*Pick your poison...* ^^

**Comment by farribeiro** [comment]
Foi aceito no flathub sem debate/questionamento, pode solicitar o encerramento desse projeto
