### ISSUE TITLE
Clarify third-party nature of package

### ISSUE THREAD

**Issue by felipehw** [flathub/br.gov.fazenda.receita.irpf#6]
First things first: Thanks for packaging this essential software for Brazilians.

It's not clear from the Flatpak description that this is a third-party package that's not maintained by the developers (SERPRO).

I'd suggest to add a message similar to the one on [various](https://flathub.org/apps/details/com.slack.Slack) [other](https://flathub.org/apps/details/com.mojang.Minecraft) [packages](https://flathub.org/apps/details/com.discordapp.Discord):

    NOTE: This wrapper is not verified by, affiliated with, or supported by SERPRO.

People should know that they're using an unofficial version.

Thanks for the initiative :D

**Comment by guihkx** [comment]
Agreed!

**Comment by guihkx** [comment]
Fixed by 58e40fe
