### ISSUE TITLE
Gnome new Platform

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf#7]
Gnome project released the v42 platform and SDK

I recommend evaluating the change, and Or don't heed this issue

Why not a PR ? I want notice and the owner make tests

**Comment by guihkx** [comment]
Thanks for the reminder, I'll schedule the GNOME runtime upgrade for the next IRPF release.

**Comment by guihkx** [comment]
Done in 1d5dbd85307e9c6a81d015327c24747b4c5f7ad9
